# Generated by Django 4.2.6 on 2023-10-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to',
            name='to_organizaton',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
