# Generated by Django 4.2.6 on 2023-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_remove_to_to_organizaton_delete_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to',
            name='data_to',
            field=models.DateField(),
        ),
    ]
